# Copyright (c) <year> <author> (<email>)
# Distributed under the MIT License.
# See accompanying file LICENSE.md or copy at http://opensource.org/licenses/MIT

language: cpp

sudo: false

compiler:
  - gcc

#before_install:
#  - bash scripts/install_cmake.sh

build_command:
    - mkdir build
    - cd build
    - cmake ..
    - make