# Copyright (c) <year> <author> (<email>)
# Distributed under the MIT License.
# See accompanying file LICENSE.md or copy at http://opensource.org/licenses/MIT

language: cpp

sudo: false

compiler:
  - gcc

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ls
  - ./Test