#ifndef INCLUDED_WINDOW_OPEN_GL_DEFINITIONS_WINDOWS_HPP_
#define INCLUDED_WINDOW_OPEN_GL_DEFINITIONS_WINDOWS_HPP_

#include <Windows.h>
#include <gl/GL.h>

#define GLAPIENTRY __stdcall

#define WGL_CONTEXT_DEBUG_BIT_ARB					0x00000001
#define WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB		0x00000002
#define WGL_CONTEXT_MAJOR_VERSION_ARB				0x2091
#define WGL_CONTEXT_MINOR_VERSION_ARB				0x2092
#define WGL_CONTEXT_LAYER_PLANE_ARB					0x2093
#define WGL_CONTEXT_FLAGS_ARB						0x2094
#define ERROR_INVALID_VERSION_ARB					0x2095

// https://www.khronos.org/registry/OpenGL/api/GL/glext.h



#endif // INCLUDED_WINDOW_OPEN_GL_DEFINITIONS_WINDOWS_HPP_